version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Build complete.
      - echo Packaging the application...
      - zip -r my-web-app.zip .
artifacts:
  files:
    - my-web-app.zip
